color0 #d8d8d8
color1 #fd4663
color2 #258c3f
color3 #8c8425
color4 #207874
color5 #9b9b9b
color6 #0e0e43
color7 #0e0e43
color8 #eff0ff
color9 #ff6079
color10 #46bf64
color11 #bfb646
color12 #3faba6
color13 #cecece
color14 #242476
color15 #242476
background #d8d8d8
selection_foreground #dadcff
cursor #207874
cursor_text_color #dadcff
foreground #0e0e43
selection_background #207874
active_border_color #207874
inactive_border_color #9b9b9b

active_tab_foreground   #dadcff
active_tab_background   #207874
inactive_tab_foreground #4b55c8
inactive_tab_background #eff0ff
cursor_trail_color      #4b55c8
