[Autologin]
Session=hyprland

[Theme]
Current=reactionary

[General]
# Forces the Qt-based greeter to scale. 2 = 200%.
GreeterEnvironment=QT_SCREEN_SCALE_FACTORS=2,QT_FONT_DPI=192

[Wayland]
EnableHiDPI=true

[X11]
EnableHiDPI=true
# Forces the X server DPI to match your Qt settings
ServerArguments=-nolisten tcp -dpi 192
